name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      solutionPath: ./Source/Sundew.TextView.ApplicationFramework.sln
      buildConfiguration: Release
      repository: 'https://sundew-dev:${{ secrets.SundewDevToken }}@github.com/hugener/Sundew.TextView.ApplicationFramework.git'
      source: 'https://api.nuget.org/v3/index.json'
      dev-source: 'https://www.myget.org/F/sundew-dev/api/v2/package'
      dev-source-latest-version: 'https://www.myget.org/F/sundew-dev/api/v3/index.json'
      pushSource: 'null'
      feedSource: 'null'
      apiKey: 'null'
      stage: 'null'
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build
      id: build
      run: >
        dotnet build ${{ env.solutionPath }} --verbosity normal --configuration ${{ env.buildConfiguration }}
        -p:"SppSourceName=${{ github.ref }}"
        '-p:"SppProductionSource=refs/heads/(?:master|main).* => ${{ env.source }}"'
        '-p:"SppIntegrationSource=refs/heads/release/.+ => ${{ env.source }}"'
        '-p:"SppDevelopmentSource=refs/heads/(?:develop.*|feature/.+|bugfix/.+) => ${{ secrets.SppDevelopmentApiKey }}@${{ env.dev-source }} {${{ env.dev-source-latest-version }}}"'
        -p:"SppAllowLocalSource=false"
        -p:"SppEnablePublish=false"
        '-p:"SppPublishLogFormats=::set-output name=pushSource::{4}|::set-output name=feedSource::{6}|::set-output name=apiKey::{5}|::set-output name=stage::{3}"'
        '-p:"SppAppendPublishFileLogFormats={0},{1}  > logs/packages.pgkver"'
        -p:"SppApiKey=${{ secrets.SppApiKey }}"
    - name: Test
      run: dotnet test ${{ env.solutionPath }} --verbosity normal --configuration ${{ env.buildConfiguration }} --no-build
    - name: Publish
      if: ${{ steps.build.outputs.pushSource != 'null' }}
      run: dotnet nuget push '**/*.nupkg' -s '${{ steps.build.outputs.pushSource }}' -k '${{ steps.build.outputs.apiKey }}'
    - name: 'Tag stable version'
      if: ${{ steps.build.outputs.stage == '' }}
      run: |
        dotnet tool update CommandLineBatcher -g
        git config user.email "sundew-dev@outlook.com"
        git config user.name "sundew-build"
        cb -c "git|tag -a {1}-{0} -m "{1}-{0}"" "git|push ${{ env.repository }} {1}-{0}" -s ',' -bf ./Source/logs/packages.pgkver
    - name: 'Wait for publish'
      if: ${{ steps.build.outputs.stage == '' }}
      run: |
        dotnet tool update Sundew.Packaging.Tool -g
        cb -c "spt|await -s ${{ steps.build.outputs.feedSource }} {0}.{1}" -s ',' -bf ./Source/logs/packages.pgkver
    



